"""initial

Revision ID: 3fa43011d101
Revises: 
Create Date: 2026-06-16 13:19:55.735082
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3fa43011d101'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('oidc_group', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_group')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_subject')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_token_token_hash'), 'api_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_token_user_id'), 'api_token', ['user_id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('nextcloud_uid', sa.String(length=255), nullable=True),
    sa.Column('nextcloud_href', sa.String(length=1024), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('vcard_raw', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=300), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emails', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('phones', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('addresses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_group_id'), 'contact', ['group_id'], unique=False)
    op.create_index(op.f('ix_contact_nextcloud_uid'), 'contact', ['nextcloud_uid'], unique=False)
    op.create_index(op.f('ix_contact_owner_id'), 'contact', ['owner_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('rrule', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('weather', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('nextcloud_uid', sa.String(length=255), nullable=True),
    sa.Column('nextcloud_href', sa.String(length=1024), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_group_id'), 'event', ['group_id'], unique=False)
    op.create_index(op.f('ix_event_nextcloud_uid'), 'event', ['nextcloud_uid'], unique=False)
    op.create_index(op.f('ix_event_owner_id'), 'event', ['owner_id'], unique=False)
    op.create_index(op.f('ix_event_starts_at'), 'event', ['starts_at'], unique=False)
    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_group_membership')
    )
    op.create_index(op.f('ix_group_membership_group_id'), 'group_membership', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_membership_user_id'), 'group_membership', ['user_id'], unique=False)
    op.create_table('journal_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cadence', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('prompts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_template_owner_id'), 'journal_template', ['owner_id'], unique=False)
    op.create_table('partnership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'partner_id', name='uq_partnership')
    )
    op.create_index(op.f('ix_partnership_owner_id'), 'partnership', ['owner_id'], unique=False)
    op.create_index(op.f('ix_partnership_partner_id'), 'partnership', ['partner_id'], unique=False)
    op.create_table('event_attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_attendee_contact_id'), 'event_attendee', ['contact_id'], unique=False)
    op.create_index(op.f('ix_event_attendee_event_id'), 'event_attendee', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_attendee_user_id'), 'event_attendee', ['user_id'], unique=False)
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['journal_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_contact_id'), 'journal_entry', ['contact_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_entry_date'), 'journal_entry', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entry_owner_id'), 'journal_entry', ['owner_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_period_key'), 'journal_entry', ['period_key'], unique=False)
    op.create_index(op.f('ix_journal_entry_template_id'), 'journal_entry', ['template_id'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('journal_template_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_template_id'], ['journal_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_event_id'), 'reminder', ['event_id'], unique=False)
    op.create_index(op.f('ix_reminder_journal_template_id'), 'reminder', ['journal_template_id'], unique=False)
    op.create_index(op.f('ix_reminder_owner_id'), 'reminder', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reminder_remind_at'), 'reminder', ['remind_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_remind_at'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_owner_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_journal_template_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_event_id'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_journal_entry_template_id'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_period_key'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_owner_id'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_entry_date'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_contact_id'), table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index(op.f('ix_event_attendee_user_id'), table_name='event_attendee')
    op.drop_index(op.f('ix_event_attendee_event_id'), table_name='event_attendee')
    op.drop_index(op.f('ix_event_attendee_contact_id'), table_name='event_attendee')
    op.drop_table('event_attendee')
    op.drop_index(op.f('ix_partnership_partner_id'), table_name='partnership')
    op.drop_index(op.f('ix_partnership_owner_id'), table_name='partnership')
    op.drop_table('partnership')
    op.drop_index(op.f('ix_journal_template_owner_id'), table_name='journal_template')
    op.drop_table('journal_template')
    op.drop_index(op.f('ix_group_membership_user_id'), table_name='group_membership')
    op.drop_index(op.f('ix_group_membership_group_id'), table_name='group_membership')
    op.drop_table('group_membership')
    op.drop_index(op.f('ix_event_starts_at'), table_name='event')
    op.drop_index(op.f('ix_event_owner_id'), table_name='event')
    op.drop_index(op.f('ix_event_nextcloud_uid'), table_name='event')
    op.drop_index(op.f('ix_event_group_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_contact_owner_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_nextcloud_uid'), table_name='contact')
    op.drop_index(op.f('ix_contact_group_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_api_token_user_id'), table_name='api_token')
    op.drop_index(op.f('ix_api_token_token_hash'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###
