"""enrichment_and_geocode

Revision ID: 54ea5b0c9513
Revises: 0df3e85b58e9
Create Date: 2026-06-16 14:58:19.457080
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '54ea5b0c9513'
down_revision: str | None = '0df3e85b58e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_event_type_owner_id'), 'life_event_type', ['owner_id'], unique=False)
    op.create_table('relationship_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('reverse_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_type_owner_id'), 'relationship_type', ['owner_id'], unique=False)
    op.create_table('contact_life_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('happened_on', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_life_event_contact_id'), 'contact_life_event', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_life_event_owner_id'), 'contact_life_event', ['owner_id'], unique=False)
    op.create_table('contact_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('from_contact_id', sa.Integer(), nullable=False),
    sa.Column('to_contact_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('reverse_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_relationship_from_contact_id'), 'contact_relationship', ['from_contact_id'], unique=False)
    op.create_index(op.f('ix_contact_relationship_owner_id'), 'contact_relationship', ['owner_id'], unique=False)
    op.create_index(op.f('ix_contact_relationship_to_contact_id'), 'contact_relationship', ['to_contact_id'], unique=False)
    op.add_column('contact', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('contact', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'longitude')
    op.drop_column('contact', 'latitude')
    op.drop_index(op.f('ix_contact_relationship_to_contact_id'), table_name='contact_relationship')
    op.drop_index(op.f('ix_contact_relationship_owner_id'), table_name='contact_relationship')
    op.drop_index(op.f('ix_contact_relationship_from_contact_id'), table_name='contact_relationship')
    op.drop_table('contact_relationship')
    op.drop_index(op.f('ix_contact_life_event_owner_id'), table_name='contact_life_event')
    op.drop_index(op.f('ix_contact_life_event_contact_id'), table_name='contact_life_event')
    op.drop_table('contact_life_event')
    op.drop_index(op.f('ix_relationship_type_owner_id'), table_name='relationship_type')
    op.drop_table('relationship_type')
    op.drop_index(op.f('ix_life_event_type_owner_id'), table_name='life_event_type')
    op.drop_table('life_event_type')
    # ### end Alembic commands ###
