"""event_types

Revision ID: 6e68afab217f
Revises: 9a86bb2f66a1
Create Date: 2026-06-16 19:27:07.721261
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6e68afab217f'
down_revision: str | None = '9a86bb2f66a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_type_owner_id'), 'event_type', ['owner_id'], unique=False)
    op.add_column('event', sa.Column('event_type', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_type')
    op.drop_index(op.f('ix_event_type_owner_id'), table_name='event_type')
    op.drop_table('event_type')
    # ### end Alembic commands ###
