"""prefs_nextcloud_links_notes

Revision ID: 9a86bb2f66a1
Revises: fb33bb269c96
Create Date: 2026-06-16 17:48:59.982529
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9a86bb2f66a1'
down_revision: str | None = 'fb33bb269c96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_note')
    )
    op.create_index(op.f('ix_event_note_event_id'), 'event_note', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_note_user_id'), 'event_note', ['user_id'], unique=False)
    op.add_column('contact', sa.Column('linked_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contact_linked_user_id'), 'contact', ['linked_user_id'], unique=False)
    op.create_foreign_key(None, 'contact', 'user', ['linked_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('user', sa.Column('default_currency', sa.String(length=3), server_default='CHF', nullable=False))
    op.add_column('user', sa.Column('phone_country_code', sa.String(length=8), server_default='+41', nullable=False))
    op.add_column('user', sa.Column('phone_number_format', sa.String(length=40), server_default='xxx xxx xx xx', nullable=False))
    op.add_column('user', sa.Column('nextcloud_url', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('nextcloud_username', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('nextcloud_app_password_enc', sa.String(length=1024), nullable=True))
    op.add_column('user', sa.Column('nextcloud_addressbook', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('nextcloud_calendar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nextcloud_calendar')
    op.drop_column('user', 'nextcloud_addressbook')
    op.drop_column('user', 'nextcloud_app_password_enc')
    op.drop_column('user', 'nextcloud_username')
    op.drop_column('user', 'nextcloud_url')
    op.drop_column('user', 'phone_number_format')
    op.drop_column('user', 'phone_country_code')
    op.drop_column('user', 'default_currency')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_index(op.f('ix_contact_linked_user_id'), table_name='contact')
    op.drop_column('contact', 'linked_user_id')
    op.drop_index(op.f('ix_event_note_user_id'), table_name='event_note')
    op.drop_index(op.f('ix_event_note_event_id'), table_name='event_note')
    op.drop_table('event_note')
    # ### end Alembic commands ###
