"""user_self_contact

Revision ID: fb33bb269c96
Revises: 54ea5b0c9513
Create Date: 2026-06-16 17:13:53.755016
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fb33bb269c96'
down_revision: str | None = '54ea5b0c9513'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('self_contact_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'self_contact_id')
    # ### end Alembic commands ###
